"""Here is the place to put all the paths necessary to run your WorldPeatlands BGP vegetation params
It is important to change these settings before running the downloaders, changing them after the downloaders
or midway through the stepped approach can cause malfunctioning of the code steps """

# the config file with your earth data credentials
EARTH_DATA_CRED = '/workspace/WorldPeatland/cred_earth_data.json'

# The root data directory is where you want your output data generated by the different code steps to be saved
ROOT_DATA_DIR = '/wp_data/sites'
