- site_area: 
  country: 
  start_date: '2013-06-01' # 'yyyy-mm-dd'
  end_date: '2023-06-30'  # 'yyyy-mm-dd'
  tiles: []
  bbox:
  
  # MODIS
- products:
  - name: Albedo
    product: MCD43A3.061
    platform: MOTA
    scaling_factor: '0.001'
    qa_def: ['BRDF_Albedo_Band_Mandatory_Quality_Band2']
    data_var: ['_Albedo_WSA_Band2']
    smooth_method: 'smoothn'
    smooth_factor: '0.5'
    period: '23'